// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TribesTable, TribesTableData } from "./tables/TribesTable.sol";
import { TribesTickers } from "./tables/TribesTickers.sol";
