// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Gates, GatesData } from "./tables/Gates.sol";
import { GatesCorpExceptions } from "./tables/GatesCorpExceptions.sol";
import { GatesCharacterExceptions } from "./tables/GatesCharacterExceptions.sol";
