// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TestTable1, TestTable1Data } from "./tables/TestTable1.sol";
import { TestTable2, TestTable2Data } from "./tables/TestTable2.sol";
import { SmartGateAccess, SmartGateAccessData } from "./tables/SmartGateAccess.sol";
