name: Deploy production

on:
  push:
    branches:
      - production

jobs:
  tests:
    uses: ./.github/workflows/foundry-tests.yml
  deploy-production:
    needs: tests
    concurrency:
      group: "deploy-production-${{github.ref}}"
      cancel-in-progress: false
    runs-on: "ubuntu-latest"
    environment: "production"
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-d14c09f15a9849fe177d097451919810e5877617
      - name: Setup Node 20.x Environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Deploy gates"
        env:
          PRIVATE_KEY: ${{ secrets.GATES_PRIVATE_KEY }}
          GATES_NAMESPACE: ${{ vars.GATES_NAMESPACE }}
        run: |
          cd packages/gates
          rm -Rf test
          npm run deploy:testnet
          npm run verify:testnet
